working on correcting \NimbusApp\Nimbus2\Nimbus\Nimbus\Nimbus.Web.Client\obj\Debug\net8.0\Nimbus.Web.Client.MvcApplicationPartsAssemblyInfo.cs(14,54,14,78): error CS0234: The type or namespace name 'ApplicationPartAttributeAttribute' does not exist in the namespace 'Microsoft.AspNetCore.Mvc.ApplicationParts'